version: '3'
services:
  db:
    image: postgres
    ports: 
      - "15432:5432"
    volumes:
      - $PWD/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secretpass
      PGDATA: /tmp
