ALTER TABLE projects 
DROP COLUMN status,
DROP COLUMN position,
DROP COLUMN name,
DROP COLUMN link,
DROP COLUMN email,
DROP COLUMN assigned_to,
DROP COLUMN date_finished,
DROP COLUMN created_at,
DROP COLUMN updated_at;