ALTER TABLE projects 
ADD COLUMN status VARCHAR NOT NULL DEFAULT 'new',
ADD COLUMN position INTEGER,
ADD COLUMN requester VARCHAR NOT NULL,
ADD COLUMN url VARCHAR,
ADD COLUMN assigned_to VARCHAR,
ADD COLUMN date_finished TIMESTAMP,
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;